import type { Metadata } from "next";
import"bootstrap-icons/font/bootstrap-icons.min.css"
import "@/style/custom.scss"
import "@/style/global.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <h1 className="titulo">HOla</h1>
        {children}
      </body>
    </html>
  );
}
